### ISSUE TITLE
Will actually streaming without taking up memory be included?

### ISSUE THREAD

**Issue by IJsLauw** [codemonument/downstream#2]
It seems the solution is right here: https://github.com/denoland/deno/issues/16544 ?

**Comment by bjesuiter** [comment]
Yes, it will stream. 
I had an error in my test, the basic functionality works. 
I attached some proofs below. 


## Test 1 - downstream a 1 GB File
<img width="805" alt="Bildschirmfoto 2023-06-10 um 13 23 02" src="https://github.com/codemonument/deno_downstream/assets/2365676/46bce28d-5a88-47ca-aef5-3c23ea53d817">

## Test 2 - downstream a 10 GB File

## In Progress
<img width="1866" alt="Bildschirmfoto 2023-06-10 um 13 37 58" src="https://github.com/codemonument/deno_downstream/assets/2365676/a377cf24-12a7-43b2-a4e0-5f5599dfcb94">

(The first deno instance is my language server, the second one is the downloading one and the third one is something I don't know, maybe the deno task instance because i started the test via a deno task) 

### The Final Result
<img width="814" alt="Bildschirmfoto 2023-06-10 um 13 43 48" src="https://github.com/codemonument/deno_downstream/assets/2365676/dd2111e0-24a4-4d43-ba78-b9ca90736a6c">


## Possible next Steps: 

You can check this for yourself by simply downloading my repo and running 
`deno task test-large`, which will run the 1 GB and 10 GB tests in series. (You can also simply comment out one of the tests to not have to wait for the whole download twice)

**Comment by bjesuiter** [comment]
I've release version 0.3.3 of this lib, with usage examples in lib and better tests. 
Please take a look at it! :)

https://deno.land/x/downstream@0.3.3
